name: webant_gallery
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7
  auto_route: ^9.2.2
  dio: ^5.8.0+1
  get_it: ^8.0.3
  dartz: ^0.10.1
  json_annotation: ^4.9.0
  internet_connection_checker_plus: ^2.7.2
  fluttertoast: ^9.0.0
  image_picker: ^1.2.1
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3
  elevated_flex: ^0.0.7
  path: ^1.9.1
  intl: ^0.20.2
  cached_network_image: ^3.4.1
  hive_flutter: ^1.1.0
  hive: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.13
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
    - family:  MyIcons
      fonts:
        - asset: assets/fonts/icons/MyIcons.ttf
